/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fluxTokenSol from "./FluxToken.sol";
export type { fluxTokenSol };
export type { FluxNFT } from "./FluxNFT";
export type { FluxVault } from "./FluxVault";
